#!/usr/bin/env bash
#install and configure nginx web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
service nginx start
