#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
