#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"


# check for the correct amount of argument
if [ -z "$1" ]
then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
elif [ -n "$2" ]
  then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi


# executet the command line arguments
if [ "$1" == "start" ]
then
  sudo ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
  [ -e "/var/run/my_process.pid" ] && sudo pkill -f "./manage_my_process" && rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
  $0 stop >& /dev/null
  $0 start >& /dev/null
  echo "manage_my_process restarted"
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi